name: complex
version: 0.7.2
#author:
#  - Richard Lincoln <r.w.lincoln@gmail.com>
#  - Frank Moreno (@kranfix) <frankmoreno1993@gmail.com>
description: A representation of a complex number, i.e. a number which has both a real and imaginary part.
homepage: https://github.com/rwl/complex

dev_dependencies:
  test: ^1.16.7
  very_good_analysis: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
